export enum NotificationType{
    MESSAGE_FEEDBACK='message_feedback',
    LOGGED_IN="logged_in",
    SIGNED_UP="signed_up",
    CONTRACT_SIGNED="contract_signed",
    CONTRACT_EXTENSION_OFFER_SENT="contract_extension_sent",
    CONTRACT_OFFER_SENT="contract_offer_sent",
    CONTRACT_EXTENSION_DECLINED="contract_extension_declined",
    CONTRACT_EXTENSION_ACCEPTED="contract_extension_accepted",
    CONTRACT_EXTENSION_COUNTER_OFFER_SENT="contract_extension_counter_offer_sent",
    CONTRACT_SIGNED_DURATION_ONE_MONTH="contract_signed_duration_one_month",
    CONTRACT_SIGNED_DURATION_THREE_MONTH="contract_signed_duration_three_month",
    CONTRACT_SIGNED_DURATION_SIX_MONTH="contract_signed_duration_six_month",
    CONTRACT_SIGNED_DURATION_ONE_YEAR="contract_signed_duration_one_year",
    LOGGED_OUT="logged_out",
    RECORD_UPDATED="record_updated",
    OTP_VERIFICATION="otp_verification",
    PASSWORD_RESET_REQUEST="password_reset_request",
    RESET_PASSWORD="reset_password",
    CHANGE_PASSWORD="change_password",
    userinfo_updated="userindo_updated",
    account_deleted="account_deleted",
    account_verified="account_verified",

    vendor_Posted="vendor_Posted",
    vendor_commented="vendor_commented",
    vendor_Updated_a_post="vendor_Updated_a_post",
    vendor_deleted_a_post="vendor_deleted_a_post",
    vendor_liked_a_post="vendor_liked_a_post",
    vendor_replied_a_comment="vendor_replied_a_comment",

    customer_Posted="customer_Posted",
    customer_commented="customer_commented",
    customer_Updated_a_post="customer_Updated_a_post",
    customer_Uploaded_a_profilePicture="customer_Updated_a_profilePicture",
    customer_deleted_a_post="customer_deleted_a_post",
    customer_liked_a_post="customer_liked_a_post",
    customer_disliked_a_post="customer_disliked_a_post",
    customer_replied_a_comment="customer_replied_a_comment",

    admin_Posted="admin_Posted",
    admin_commented="admin_commented",
    admin_Updated_a_post="admin_Updated_a_post",
    admin_deleted_a_post="admin_deleted_a_post",
    admin_liked_a_post="admin_liked_a_post",
    admin_replied_a_comment="admin_replied_a_comment",

    model_Posted="model_Posted",
    model_commented="model_commented",
    model_Updated_a_post="model_Updated_a_post",
    model_deleted_a_post="model_deleted_a_post",
    model_liked_a_post="model_liked_a_post",
    model_replied_a_comment="model_replied_a_comment",

    photographer_Posted="photographer_Posted",
    photographer_commented="photographer_commented",
    photographer_Updated_a_post="photographerr_Updated_a_post",
    photographer_deleted_a_post="photographer_deleted_a_post",
    photographer_liked_a_post="photographer_liked_a_post",
    photographer_replied_a_comment="photographer_replied_a_comment",



}