export enum NotificationType{
    MESSAGE_FEEDBACK='message_feedback',
    LOGGED_IN="logged_in",
    SIGNED_UP="signed_up",
    CONTRACT_SIGNED="contract_signed",
    CONTRACT_EXTENSION_OFFER_SENT="contract_extension_sent",
    CONTRACT_EXTENSION_DECLINED="contract_extension_declined",
    CONTRACT_EXTENSION_ACCEPTED="contract_extension_accepted",
    CONTRACT_EXTENSION_COUNTER_OFFER_SENT="contract_extension_counter_offer_sent",
    CONTRACT_SIGNED_DURATION_ONE_MONTH="contract_signed_duration_one_month",
    CONTRACT_SIGNED_DURATION_THREE_MONTH="contract_signed_duration_three_month",
    CONTRACT_SIGNED_DURATION_SIX_MONTH="contract_signed_duration_six_month",
    CONTRACT_SIGNED_DURATION_ONE_YEAR="contract_signed_duration_one_year",
    LOGGED_OUT="logged_out",
    RECORD_UPDATED="record_updated",
    OTP_VERIFICATION="otp_verification",
    PASSWORD_RESET_REQUEST="password_reset_request",
    RESET_PASSWORD="reset_password",
    CHANGE_PASSWORD="change_password",
    userinfo_updated="userindo_updated",
    account_deleted="account_deleted",
    account_verified="account_verified",

}